### ISSUE TITLE
Proxy consume all resources and doesn't release

### ISSUE THREAD

**Issue by gigimon** [neonevm/proxy-model.py#497]
Proxy (version Neon-proxy/v0.5.4-dev-472aa556b63cfdd2db90c8ff22b0c30f4d07281d) consume all resources when we run openzeppelin tests and doesn't release it over time.

We run openzeppelin for 8 threads and after 7 minutes, proxy in docker consume 20 Gb RAM and create more than 2000 threads. When we stop tests, wait 10 minutes, proxy still eat 21 Gb RAM and have a more than 2000 threads in peak.

We have compared this with release stand and on it proxy eat 500-600 Mb RAM and 100-200 threads.

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/618b73ecce1e8845a5e6332c/06fc1d9b-6ddb-40fd-b8ac-726edfc5dcc2)
![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/618b73ecce1e8845a5e6332c/61d5e114-086e-4ac0-ab22-2235da6b5b9c)

**Comment by afalaleev** [comment]
The first investigation shows that proxy has problems with a long history of neon transactions.
It doesn't free some structures and that is why it uses a lot of memory.

To resolve the issue more information should be logged.

**Comment by afalaleev** [comment]
This is not indexer.
Proxy uses a lot of memory on handling client requests.
When a lot of process with high memory usage, oom killer kills some of them and proxy stops accepting connections.
IMHO the route cause of the issue is in db.
Test stand has big database, and proxy requests block number from db without limit and take only the first record.
